theme: jekyll-theme-slate


**Bold**
_Italic_
`Code`
# The Giant Worm


- We are Working Together
- To become one


  _How Do You Stop IT_  
  **DoYouKnowDaWay**

[Link](https://imgur.com/user/Swisherr) 

##Images

Image:

![](https://imgur.com/JHRHuZw)

> Spooky Night.

### Header 3

1. Do not try to stop the wave
2. You will Drown!
